#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.8f1_fc0fe30d6d91"
#define UNITY_VERSION_FULL_NICE "2018.3.8f1 (fc0fe30d6d91)"
#define UNITY_VERSION_BLD 16519139
#define UNITY_VERSION_DATE 1551776481
#define UNITY_VERSION_WIN "2018.3.8.16519139"
#define UNITY_VERSION_BRANCH "2018.3/staging"
